#!/bin/bash

#JAVA
if which jenv > /dev/null; then
    cd "$(jenv root)"
	git pull
    cd $HOME
fi

# node
if which nodenv > /dev/null; then
    cd "$(nodenv root)"
	git pull
    cd "$(nodenv root)"/plugins/node-build
	git pull
    cd $HOME
fi

# ruby 
if which rbenv > /dev/null; then
    cd "$(rbenv root)"
	git pull
    cd "$(rbenv root)"/plugins/ruby-build
	git pull
    cd $HOME
fi

# python
if which pyenv > /dev/null; then
    cd "$(pyenv root)"
	git pull
    cd $HOME
fi

# php
if which phpenv > /dev/null; then
    cd "$(phpenv root)"
	git pull
    cd $(phpenv root)/plugins/php-build
    git pull
    cd $(phpenv root)/plugins/phpenv-composer
    git pull
    cd $HOME
fi

# go
if which goenv > /dev/null; then
    cd "$(goenv root)"
    git pull
    cd $HOME
fi